### ISSUE TITLE
🐛 Trying to run Rome in a fresh Vue CLI project fails immediately.

### ISSUE THREAD

**Issue by jakedohm** [romefrontend/rome#1022] opened 2020-08-10 15:11 UTC
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/var/folders/yr/1ls23_c52dbd7mh7133r7j600000gn/T/yarn--1597072062311-0.8606840415445174:/Users/jakedohm/Sites/rome-vue/node_modul
    es/.bin:/Users/jakedohm/.config/yarn/link/node_modules/.bin:/usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node
    _modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/Users/jakedohm/.composer/vendor/bin:/usr/local/bin:/usr/
    bin:/bin:/usr/sbin:/sbin:/Users/jakedohm/.composer/vendor/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "jakedohm"
  }

User Config
  unset

Rome Version
  10.0.3-beta

Node Version
  13.13.0

Platform
  darwin x64 19.4.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 144
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/jakedohm/Sites/rome-vue"
    realCwd: "/Users/jakedohm/Sites/rome-vue"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_312_704
      pid: 41_101
      uptime: 0.215673518
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_312_704
        ownedBytes: 0
        ownedFileCount: 0
        pid: 41_101
        uptime: 0.215608761
      }
    ]
  }
```

## Steps To Reproduce

1. Run `vue create rome-vue`
2. Run `cd rome-vue`
3. Run `rome init --apply`

## Expected Results

I expected Rome to start linting, and run some codemods to change the default Vue CLI code formatting.

## Actual Result

Rome fell over, providing me with the following error
> Cannot construct a FilePath with zero segments
> ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

**Comment by sebmck** [comment] 2020-08-10 23:37
Duplicate of #990.

**Closed by sebmck** 2020-08-10 23:37 UTC
Labels: bug: unconfirmed
